version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: demo
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: demo
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
